try {
    console.loge(4)
} catch (error) {
    console.log(error)
    
}

console.log(5)